// <auto-generated />
using System;
using AccessControl.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccessControl.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251110161958_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccessControl.Domain.Entities.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fd62efee-c22c-432d-9b6b-1ed0cceea663"),
                            CreatedAt = new DateTime(2025, 11, 10, 16, 19, 57, 712, DateTimeKind.Utc).AddTicks(4553),
                            Icon = "LayoutDashboard",
                            IsActive = true,
                            Name = "Dashboard",
                            Path = "/dashboard"
                        },
                        new
                        {
                            Id = new Guid("e4109e58-ac11-4cb9-a538-710ee4b07afe"),
                            CreatedAt = new DateTime(2025, 11, 10, 16, 19, 57, 712, DateTimeKind.Utc).AddTicks(4757),
                            Icon = "CarFront",
                            IsActive = true,
                            Name = "Visits",
                            Path = "/visits"
                        },
                        new
                        {
                            Id = new Guid("b7dabed6-e654-4ba6-9f50-a0dc2f24e9ac"),
                            CreatedAt = new DateTime(2025, 11, 10, 16, 19, 57, 712, DateTimeKind.Utc).AddTicks(4786),
                            Icon = "Users",
                            IsActive = true,
                            Name = "Users",
                            Path = "/users"
                        });
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.Residence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Identifier");

                    b.HasIndex("OwnerId");

                    b.ToTable("Residences");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0dfde6e-ebda-4809-864d-3c7ee8d5989e"),
                            CreatedAt = new DateTime(2025, 11, 10, 16, 19, 57, 712, DateTimeKind.Utc).AddTicks(4384),
                            Identifier = "RES-001",
                            IsActive = true,
                            OwnerId = new Guid("5afe1bf5-2e00-4e38-a0d9-0e80c8418303")
                        });
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.RoleMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("Role", "MenuId")
                        .IsUnique();

                    b.ToTable("RoleMenus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5dc4fb40-b77f-4c73-8291-9a65104898cf"),
                            MenuId = new Guid("fd62efee-c22c-432d-9b6b-1ed0cceea663"),
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("01c2109a-a25d-4d59-98bc-5770224198a8"),
                            MenuId = new Guid("e4109e58-ac11-4cb9-a538-710ee4b07afe"),
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("09647dd5-1574-45a7-a969-d7a38859e3b8"),
                            MenuId = new Guid("b7dabed6-e654-4ba6-9f50-a0dc2f24e9ac"),
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("117fa697-5f7c-4930-8a47-707c1b9adef8"),
                            MenuId = new Guid("fd62efee-c22c-432d-9b6b-1ed0cceea663"),
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("bb56a956-9acd-4188-a1a1-b88917559b55"),
                            MenuId = new Guid("e4109e58-ac11-4cb9-a538-710ee4b07afe"),
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("364a06eb-de3b-48b2-82f4-519d94a511e6"),
                            MenuId = new Guid("fd62efee-c22c-432d-9b6b-1ed0cceea663"),
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("58dc24c9-683a-463e-a4a3-2f7bd4ee9e15"),
                            MenuId = new Guid("e4109e58-ac11-4cb9-a538-710ee4b07afe"),
                            Role = 2
                        });
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApartmentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c4daa537-604b-48f8-880a-9a49b0ab5d56"),
                            ApartmentNumber = "001",
                            CreatedAt = new DateTime(2025, 11, 10, 16, 19, 57, 308, DateTimeKind.Utc).AddTicks(4282),
                            Email = "admin@accesscontrol.com",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "User",
                            PasswordHash = "$2a$11$h5VJArtUEPEf.a4mzXU.wuPBuxT0XLCS2D.mlEPTZBn99f3Ar0vaa",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("5afe1bf5-2e00-4e38-a0d9-0e80c8418303"),
                            ApartmentNumber = "101",
                            CreatedAt = new DateTime(2025, 11, 10, 16, 19, 57, 510, DateTimeKind.Utc).AddTicks(7210),
                            Email = "owner@accesscontrol.com",
                            FirstName = "John",
                            IsActive = true,
                            LastName = "Doe",
                            PasswordHash = "$2a$11$baw5u69n3UpBglq4A2k2ZeO3X1qk6NSgjXbdBvXjUAenqiIBsKCLq",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("564ea613-4aa7-48bb-9fcc-c97bfe77122b"),
                            ApartmentNumber = "002",
                            CreatedAt = new DateTime(2025, 11, 10, 16, 19, 57, 712, DateTimeKind.Utc).AddTicks(2800),
                            Email = "guard@accesscontrol.com",
                            FirstName = "Guard",
                            IsActive = true,
                            LastName = "User",
                            PasswordHash = "$2a$11$4HxulFqrdJSL40CC9c0PEuKTHzUjxCIKE9c95JCQOmTHDhphaYv.i",
                            Role = 1
                        });
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.Visit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RegisteredById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResidenceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VehiclePlate")
                        .HasColumnType("text");

                    b.Property<string>("VisitorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VisitorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RegisteredById");

                    b.HasIndex("ResidenceId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.Residence", b =>
                {
                    b.HasOne("AccessControl.Domain.Entities.User", "Owner")
                        .WithMany("Residences")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.RoleMenu", b =>
                {
                    b.HasOne("AccessControl.Domain.Entities.Menu", "Menu")
                        .WithMany("RoleMenus")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.Visit", b =>
                {
                    b.HasOne("AccessControl.Domain.Entities.User", "RegisteredBy")
                        .WithMany()
                        .HasForeignKey("RegisteredById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccessControl.Domain.Entities.Residence", "Residence")
                        .WithMany()
                        .HasForeignKey("ResidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegisteredBy");

                    b.Navigation("Residence");
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.Menu", b =>
                {
                    b.Navigation("RoleMenus");
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.User", b =>
                {
                    b.Navigation("Residences");
                });
#pragma warning restore 612, 618
        }
    }
}
