// <auto-generated />
using System;
using AccessControl.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccessControl.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251110160919_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccessControl.Domain.Entities.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("70c1e2e6-410f-4bcd-b25f-59a2723c46c4"),
                            CreatedAt = new DateTime(2025, 11, 10, 16, 9, 17, 632, DateTimeKind.Utc).AddTicks(6771),
                            IsActive = true,
                            Name = "Dashboard",
                            Path = "/dashboard"
                        },
                        new
                        {
                            Id = new Guid("e37221d9-a167-4302-8af9-ae9454e5139d"),
                            CreatedAt = new DateTime(2025, 11, 10, 16, 9, 17, 632, DateTimeKind.Utc).AddTicks(6786),
                            IsActive = true,
                            Name = "Visits",
                            Path = "/visits"
                        },
                        new
                        {
                            Id = new Guid("72cf8d54-d378-4fbf-b405-3b9aba54054f"),
                            CreatedAt = new DateTime(2025, 11, 10, 16, 9, 17, 632, DateTimeKind.Utc).AddTicks(6814),
                            IsActive = true,
                            Name = "Users",
                            Path = "/users"
                        });
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.Residence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Identifier");

                    b.HasIndex("OwnerId");

                    b.ToTable("Residences");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0d98e5eb-7a34-4953-95cd-5ac0bb558f5e"),
                            CreatedAt = new DateTime(2025, 11, 10, 16, 9, 17, 632, DateTimeKind.Utc).AddTicks(6611),
                            Identifier = "RES-001",
                            IsActive = true,
                            OwnerId = new Guid("64a11d2f-3b49-4c68-a6b7-be16ed0b5f0c")
                        });
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.RoleMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("Role", "MenuId")
                        .IsUnique();

                    b.ToTable("RoleMenus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("918e0c20-692c-4727-bc06-95e492901b3b"),
                            MenuId = new Guid("70c1e2e6-410f-4bcd-b25f-59a2723c46c4"),
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("24e0ece9-1388-4919-8573-9d683561a3a8"),
                            MenuId = new Guid("e37221d9-a167-4302-8af9-ae9454e5139d"),
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("69a69007-a723-4bf3-aed0-db9facfae7df"),
                            MenuId = new Guid("72cf8d54-d378-4fbf-b405-3b9aba54054f"),
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("eec202fc-ea5b-4d42-8545-7564e4123bc0"),
                            MenuId = new Guid("70c1e2e6-410f-4bcd-b25f-59a2723c46c4"),
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("b75b15d5-75bb-4c2c-9f6c-e048282b833f"),
                            MenuId = new Guid("e37221d9-a167-4302-8af9-ae9454e5139d"),
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("cc22db92-d9aa-40a6-8cf2-238252f52539"),
                            MenuId = new Guid("70c1e2e6-410f-4bcd-b25f-59a2723c46c4"),
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("a5dece41-cfc3-496a-82f1-fa8e0a544a31"),
                            MenuId = new Guid("e37221d9-a167-4302-8af9-ae9454e5139d"),
                            Role = 2
                        });
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApartmentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("003e0a7f-f42d-4a41-bd7a-3951dcc2c5ca"),
                            ApartmentNumber = "001",
                            CreatedAt = new DateTime(2025, 11, 10, 16, 9, 17, 228, DateTimeKind.Utc).AddTicks(7255),
                            Email = "admin@accesscontrol.com",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "User",
                            PasswordHash = "$2a$11$dJXYBidufZNnTvlRGDsChuaVzI7tqrmBkfd16nAaWXXO7F9snPizG",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("64a11d2f-3b49-4c68-a6b7-be16ed0b5f0c"),
                            ApartmentNumber = "101",
                            CreatedAt = new DateTime(2025, 11, 10, 16, 9, 17, 432, DateTimeKind.Utc).AddTicks(1847),
                            Email = "owner@accesscontrol.com",
                            FirstName = "John",
                            IsActive = true,
                            LastName = "Doe",
                            PasswordHash = "$2a$11$qhul2mDDa.bP/iE/4P.pzuSaxXBy3yG8PKO8MgKTwDDUrqGmQqX4W",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("a5e0389f-38a2-4e0a-91f2-3ad0fdb78c12"),
                            ApartmentNumber = "002",
                            CreatedAt = new DateTime(2025, 11, 10, 16, 9, 17, 632, DateTimeKind.Utc).AddTicks(5190),
                            Email = "guard@accesscontrol.com",
                            FirstName = "Guard",
                            IsActive = true,
                            LastName = "User",
                            PasswordHash = "$2a$11$uMckiZ1YRxLqisKsh82N2eX/OjOd9loD/6n4e33VT8YC48S4WkvEu",
                            Role = 1
                        });
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.Visit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RegisteredById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResidenceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VehiclePlate")
                        .HasColumnType("text");

                    b.Property<string>("VisitorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VisitorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RegisteredById");

                    b.HasIndex("ResidenceId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.Residence", b =>
                {
                    b.HasOne("AccessControl.Domain.Entities.User", "Owner")
                        .WithMany("Residences")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.RoleMenu", b =>
                {
                    b.HasOne("AccessControl.Domain.Entities.Menu", "Menu")
                        .WithMany("RoleMenus")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.Visit", b =>
                {
                    b.HasOne("AccessControl.Domain.Entities.User", "RegisteredBy")
                        .WithMany()
                        .HasForeignKey("RegisteredById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccessControl.Domain.Entities.Residence", "Residence")
                        .WithMany()
                        .HasForeignKey("ResidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegisteredBy");

                    b.Navigation("Residence");
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.Menu", b =>
                {
                    b.Navigation("RoleMenus");
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.User", b =>
                {
                    b.Navigation("Residences");
                });
#pragma warning restore 612, 618
        }
    }
}
