// <auto-generated />
using System;
using AccessControl.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccessControl.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251121234739_AddPersonEntityV2")]
    partial class AddPersonEntityV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccessControl.Domain.Entities.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9452df48-5b92-40ef-829e-a315c01aadcb"),
                            CreatedAt = new DateTime(2025, 11, 21, 23, 47, 38, 845, DateTimeKind.Utc).AddTicks(1924),
                            Icon = "LayoutDashboard",
                            IsActive = true,
                            Name = "Dashboard",
                            Order = 1,
                            Path = "/dashboard"
                        },
                        new
                        {
                            Id = new Guid("a509d9b3-9c77-4324-bc20-4a004b8c5abf"),
                            CreatedAt = new DateTime(2025, 11, 21, 23, 47, 38, 845, DateTimeKind.Utc).AddTicks(1941),
                            Icon = "CarFront",
                            IsActive = true,
                            Name = "Visits",
                            Order = 2,
                            Path = "/visits"
                        },
                        new
                        {
                            Id = new Guid("d8fcac7d-c0ea-4cd5-8ad0-92b33953a142"),
                            CreatedAt = new DateTime(2025, 11, 21, 23, 47, 38, 845, DateTimeKind.Utc).AddTicks(1962),
                            Icon = "Users",
                            IsActive = true,
                            Name = "Users",
                            Order = 3,
                            Path = "/users"
                        });
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PersonType")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DocumentNumber")
                        .IsUnique();

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.Residence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Identifier");

                    b.HasIndex("OwnerId");

                    b.ToTable("Residences");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8c885dcd-3734-45b6-9b7e-633351852714"),
                            CreatedAt = new DateTime(2025, 11, 21, 23, 47, 38, 845, DateTimeKind.Utc).AddTicks(1777),
                            Identifier = "RES-001",
                            IsActive = true,
                            OwnerId = new Guid("e790170c-4407-4cff-8358-8f6a09a46fad")
                        });
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.RoleMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("Role", "MenuId")
                        .IsUnique();

                    b.ToTable("RoleMenus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9ea9bd6d-11ee-4d47-acaa-32fce37c34d0"),
                            MenuId = new Guid("9452df48-5b92-40ef-829e-a315c01aadcb"),
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("c70ee399-2739-4d76-a6a5-b4848f7273e3"),
                            MenuId = new Guid("a509d9b3-9c77-4324-bc20-4a004b8c5abf"),
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("e650bfce-65ef-416e-8f10-f56fa43a6edc"),
                            MenuId = new Guid("d8fcac7d-c0ea-4cd5-8ad0-92b33953a142"),
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("d2370f28-6288-4482-a93c-7849648a5991"),
                            MenuId = new Guid("9452df48-5b92-40ef-829e-a315c01aadcb"),
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("8c1587ae-f51b-48c6-97d6-04f31b3c057c"),
                            MenuId = new Guid("a509d9b3-9c77-4324-bc20-4a004b8c5abf"),
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("9b05f72c-eadb-49ec-84bf-f895d549f5cc"),
                            MenuId = new Guid("9452df48-5b92-40ef-829e-a315c01aadcb"),
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("bc524814-0d6b-4ff7-a227-2fa9c1ad589e"),
                            MenuId = new Guid("a509d9b3-9c77-4324-bc20-4a004b8c5abf"),
                            Role = 2
                        });
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApartmentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ca682896-4e5f-4e3c-a3f0-f19627a71f93"),
                            ApartmentNumber = "001",
                            CreatedAt = new DateTime(2025, 11, 21, 23, 47, 38, 434, DateTimeKind.Utc).AddTicks(4783),
                            Email = "admin@accesscontrol.com",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "User",
                            PasswordHash = "$2a$11$NrwVmJEOdhpPYxIjwzhi8e79QrYbaW25WmXZXTOPwq70vuN4Rpl/S",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("e790170c-4407-4cff-8358-8f6a09a46fad"),
                            ApartmentNumber = "101",
                            CreatedAt = new DateTime(2025, 11, 21, 23, 47, 38, 641, DateTimeKind.Utc).AddTicks(7232),
                            Email = "owner@accesscontrol.com",
                            FirstName = "John",
                            IsActive = true,
                            LastName = "Doe",
                            PasswordHash = "$2a$11$ftyFUyavOWRp2SriTa84WuU8QeoAjQV/9OhC1J3QzojVsjITw/osi",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("1a8553d6-0dee-4c79-aa40-2c41c68cd698"),
                            ApartmentNumber = "002",
                            CreatedAt = new DateTime(2025, 11, 21, 23, 47, 38, 845, DateTimeKind.Utc).AddTicks(327),
                            Email = "guard@accesscontrol.com",
                            FirstName = "Guard",
                            IsActive = true,
                            LastName = "User",
                            PasswordHash = "$2a$11$bKkXvLrTLRP4MzUnYuL6Zu1S9g7g.dUolC/DcZxHqApI9YMZco45u",
                            Role = 1
                        });
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.Visit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegisteredById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResidenceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VehiclePlate")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("RegisteredById");

                    b.HasIndex("ResidenceId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.Residence", b =>
                {
                    b.HasOne("AccessControl.Domain.Entities.User", "Owner")
                        .WithMany("Residences")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.RoleMenu", b =>
                {
                    b.HasOne("AccessControl.Domain.Entities.Menu", "Menu")
                        .WithMany("RoleMenus")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.Visit", b =>
                {
                    b.HasOne("AccessControl.Domain.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccessControl.Domain.Entities.User", "RegisteredBy")
                        .WithMany()
                        .HasForeignKey("RegisteredById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccessControl.Domain.Entities.Residence", "Residence")
                        .WithMany()
                        .HasForeignKey("ResidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("RegisteredBy");

                    b.Navigation("Residence");
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.Menu", b =>
                {
                    b.Navigation("RoleMenus");
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.User", b =>
                {
                    b.Navigation("Residences");
                });
#pragma warning restore 612, 618
        }
    }
}
