// <auto-generated />
using System;
using AccessControl.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccessControl.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251110203229_AddOrderToMenu")]
    partial class AddOrderToMenu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccessControl.Domain.Entities.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("884af528-cae0-4da4-9c6c-443020d1c6d3"),
                            CreatedAt = new DateTime(2025, 11, 10, 20, 32, 29, 45, DateTimeKind.Utc).AddTicks(7725),
                            Icon = "LayoutDashboard",
                            IsActive = true,
                            Name = "Dashboard",
                            Order = 1,
                            Path = "/dashboard"
                        },
                        new
                        {
                            Id = new Guid("a6ba19e3-61a5-4e50-a2b6-566a8e6f8af0"),
                            CreatedAt = new DateTime(2025, 11, 10, 20, 32, 29, 45, DateTimeKind.Utc).AddTicks(7740),
                            Icon = "CarFront",
                            IsActive = true,
                            Name = "Visits",
                            Order = 2,
                            Path = "/visits"
                        },
                        new
                        {
                            Id = new Guid("239d0797-0293-4387-8e0f-3f94cb66f732"),
                            CreatedAt = new DateTime(2025, 11, 10, 20, 32, 29, 45, DateTimeKind.Utc).AddTicks(7769),
                            Icon = "Users",
                            IsActive = true,
                            Name = "Users",
                            Order = 3,
                            Path = "/users"
                        });
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.Residence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Identifier");

                    b.HasIndex("OwnerId");

                    b.ToTable("Residences");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3d06fa45-a3a9-4f21-9910-b857fc0b0827"),
                            CreatedAt = new DateTime(2025, 11, 10, 20, 32, 29, 45, DateTimeKind.Utc).AddTicks(7571),
                            Identifier = "RES-001",
                            IsActive = true,
                            OwnerId = new Guid("628de891-c810-469f-aadc-adfccb6df6a0")
                        });
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.RoleMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("Role", "MenuId")
                        .IsUnique();

                    b.ToTable("RoleMenus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1789395f-3112-4e0b-b67e-4daf9548cfbe"),
                            MenuId = new Guid("884af528-cae0-4da4-9c6c-443020d1c6d3"),
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("026d9c28-a8cf-4ed2-a02c-a4cab699734a"),
                            MenuId = new Guid("a6ba19e3-61a5-4e50-a2b6-566a8e6f8af0"),
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("81ff1a4d-919a-4aed-9136-961598d376d2"),
                            MenuId = new Guid("239d0797-0293-4387-8e0f-3f94cb66f732"),
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("72b0373f-6fd7-4ac2-9640-cc78bddaa087"),
                            MenuId = new Guid("884af528-cae0-4da4-9c6c-443020d1c6d3"),
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("7674abc5-0541-4469-b776-cdf1a0b5482c"),
                            MenuId = new Guid("a6ba19e3-61a5-4e50-a2b6-566a8e6f8af0"),
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("d656dbfd-7706-4eec-9b99-9a4f1c6a5544"),
                            MenuId = new Guid("884af528-cae0-4da4-9c6c-443020d1c6d3"),
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("4b90d743-15d4-4443-9f96-33aa9917768c"),
                            MenuId = new Guid("a6ba19e3-61a5-4e50-a2b6-566a8e6f8af0"),
                            Role = 2
                        });
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApartmentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eaa6a665-7a14-447b-a7df-aa83c6ba96b6"),
                            ApartmentNumber = "001",
                            CreatedAt = new DateTime(2025, 11, 10, 20, 32, 28, 639, DateTimeKind.Utc).AddTicks(9255),
                            Email = "admin@accesscontrol.com",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "User",
                            PasswordHash = "$2a$11$tYY2TwNWa.JdcBT8tuSb/Oc5EogV0vbq0a7A4Il7wtmduMJw2YhcO",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("628de891-c810-469f-aadc-adfccb6df6a0"),
                            ApartmentNumber = "101",
                            CreatedAt = new DateTime(2025, 11, 10, 20, 32, 28, 845, DateTimeKind.Utc).AddTicks(9618),
                            Email = "owner@accesscontrol.com",
                            FirstName = "John",
                            IsActive = true,
                            LastName = "Doe",
                            PasswordHash = "$2a$11$gbsnApsyPF1tOTZeoc6qEuly0HZiLtdbpnLgEoBd40YEhy7ul1i5O",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("5d60b48f-f0c2-4f95-918d-5c5c76f89eff"),
                            ApartmentNumber = "002",
                            CreatedAt = new DateTime(2025, 11, 10, 20, 32, 29, 45, DateTimeKind.Utc).AddTicks(6299),
                            Email = "guard@accesscontrol.com",
                            FirstName = "Guard",
                            IsActive = true,
                            LastName = "User",
                            PasswordHash = "$2a$11$6cX3ymDNWZ.EtQk4ulMOPubkwXex7d6ZF2QmeHNitT3hWE6R3xY6q",
                            Role = 1
                        });
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.Visit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RegisteredById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResidenceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VehiclePlate")
                        .HasColumnType("text");

                    b.Property<string>("VisitorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VisitorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RegisteredById");

                    b.HasIndex("ResidenceId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.Residence", b =>
                {
                    b.HasOne("AccessControl.Domain.Entities.User", "Owner")
                        .WithMany("Residences")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.RoleMenu", b =>
                {
                    b.HasOne("AccessControl.Domain.Entities.Menu", "Menu")
                        .WithMany("RoleMenus")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.Visit", b =>
                {
                    b.HasOne("AccessControl.Domain.Entities.User", "RegisteredBy")
                        .WithMany()
                        .HasForeignKey("RegisteredById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccessControl.Domain.Entities.Residence", "Residence")
                        .WithMany()
                        .HasForeignKey("ResidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegisteredBy");

                    b.Navigation("Residence");
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.Menu", b =>
                {
                    b.Navigation("RoleMenus");
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.User", b =>
                {
                    b.Navigation("Residences");
                });
#pragma warning restore 612, 618
        }
    }
}
